services:
  - type: web
    name: dtm-math-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_INVITE_CODE
        value: dtm2024secret
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
